name: "Cleanup Action"
description: "Removes unnecessary pre-installed software to free up space"

runs:
  using: "composite"
  steps:
    - name: Clean up unnecessary pre-installed software
      shell: bash
      run: |
        echo "Storage before cleanup - "
        df -h

        sudo rm -rf /usr/lib/jvm
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /opt/microsoft /opt/google
        sudo rm -rf /opt/az
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /opt/hostedtoolcache

        docker system prune -af || true
        docker builder prune -af || true

        echo "Storage after cleanup - "
        df -h
